### ISSUE TITLE
CUDA: an illegal memory access was encountered

### ISSUE THREAD

**Issue by CharliedoD** [mm-graph-benchmark/mm-graph-benchmark#1]
Could you provide a detailed requirement document? There was an illegal modification of CUDA memory during execution, and a similar error occurred when running on the CPU.

dgl._ffi.base.DGLError: [12:48:37] /opt/dgl/src/array/cuda/rowwise_sampling.cu:332: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered

**Comment by twelfth-star** [comment]
Thank you for your interest in our paper and code! Could you please provide us with your code to reproduce the error?

**Comment by CharliedoD** [comment]
Thank you for your attention. I made some modifications to the main.py file to ensure the code can run up to the train function. However, when running the line of code:
for it, (input_nodes, pair_graph, neg_pair_graph, blocks) in enumerate(dataloader):
an error occurred. The main.py is shown in the attachment. 
[main.txt](https://github.com/user-attachments/files/16062159/main.txt)
![1719898068537](https://github.com/mm-graph-benchmark/mm-graph-benchmark/assets/117720770/c77a31ed-2bd0-418b-a06b-82193eae0b99)

**Comment by CharliedoD** [comment]
I've shortened main.py to 70 lines for your convenience in viewing the error, but it still reports the same error. :
import torch
from utils import Logger, to_bidirected_with_reverse_mapping, load_usair_dataset, load_esci_dataset, \
    remove_collab_dissimilar_edges
import torch.nn.functional as F
import dgl
from dgl.dataloading import DataLoader, NeighborSampler, MultiLayerFullNeighborSampler, as_edge_prediction_sampler, \
    negative_sampler
import tqdm
from models import SAGE, GCN, MLP, Dot, GATv2
import os
import numpy as np
from sklearn import metrics
import pickle
import pdb
import hydra
import logging
from omegaconf import DictConfig, OmegaConf
import time
import optuna
from lp_dataset import LinkPredictionDataset, LinkPredictionEvaluator

PROJETC_DIR = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(PROJETC_DIR, '../')
CONFIG_DIR = os.path.join(PROJETC_DIR, "configs")
log = logging.getLogger(__name__)




@hydra.main(config_path=CONFIG_DIR, config_name="defaults", version_base='1.2')
def main(cfg: DictConfig):
    log.info('Loading data')
    data_path = 'data/' # replace this with the path where you save the datasets
    dataset_name = 'sports-copurchase'
    feat_name = 't5vit'
    edge_split_type = 'hard'
    verbose = True
    device = 'cuda:1' # use 'cuda' if GPU is available
    print(os.path.join(data_path, dataset_name))
    dataset = LinkPredictionDataset(
        root=os.path.join(data_path, dataset_name),
        feat_name=feat_name,
        edge_split_type=edge_split_type,
        verbose=verbose,
        device=device
    )

    g = dataset.graph
    
    # type(graph) would be dgl.DGLGraph
    # use graph.ndata['feat'] to get the features

    edge_split = dataset.get_edge_split()
    g = dgl.remove_self_loop(g)
    log.info("remove isolated nodes")
    g = g.to('cpu')
    g, reverse_eids = to_bidirected_with_reverse_mapping(g)
    g = g.to('cuda:1' if cfg.mode == 'puregpu' else 'cpu')
    num_nodes = g.number_of_nodes()
    reverse_eids = reverse_eids.to(device)
    seed_edges = torch.arange(g.num_edges()).to(device)
    
    
    sampler = NeighborSampler([cfg.num_of_neighbors] * cfg.num_layers, prefetch_node_feats=['feat'])
    dataloader = DataLoader(
        g, seed_edges, sampler,
        device=device, batch_size=cfg.batch_size, shuffle=True,
        drop_last=False, num_workers=0, use_uva=False)
        
    for input_nodes, output_nodes, blocks in dataloader:
        print(input_nodes)

if __name__=='__main__':
    main()

**Comment by CharliedoD** [comment]
I've shortened main.py to 70 lines for your convenience in viewing the error, but it still reports the same error. 
[mainpy.txt](https://github.com/user-attachments/files/16062257/mainpy.txt)

**Comment by jwzhi** [comment]
It's mostly because the model code is written in DGL 1.0.1 and CUDA 11.6.2. If you want to use the model script right now, you will need to reinstall DGL to 1.0.1. We plan to update that to the newer DGL versions. I will let you know when I finished it. 

In the meantime, if you only want to use the dataset, it should work in the latest DGL smoothly. 

Thank you,
Jing

**Comment by jwzhi** [comment]
Hi @CharliedoD, thanks for bringing this up. It seems that I accidentally cleaned out the edge sampler when uploading the code. I have fixed this. And it works on my side. When you have time, can you please try to pull it one more time and have another try to see if this fixes your issues? 

Thank you and let us know if you have any other questions. 

Jing

**Comment by CharliedoD** [comment]
Thank you, I ran the code again and found that the code works with the addition of the edge sampler. 

FYI there seems to be some minor errors in the main.py file of nc, e.g. Lines 253-255 maybe should add 'g.' before 'ndata', and the shape of 'splits['train_idx']', 'splits['val_idx']', and 'splits['test_idx ']' are 2D, maybe I should add '.view(-1)' to change them to 1D, these errors may be due to my Lib version.

Another small problem, the lp-edge-split in the dataset Sports doesn't specify what type of edge split it is, 'hard' or others?

 I hope you'll take note of it. Thanks for providing a meaningful multimodal graph benchmark!

**Comment by CharliedoD** [comment]
FYI there seems to be some minor errors in the main.py file of nc, e.g.    Lines 253-255 maybe should add 'g.' before 'ndata', and the shape of 'splits['train_idx']', 'splits['val_idx']', and 'splits['test_idx ']' are 2D, maybe I should add '.view(-1)' to change them to 1D, these errors may be due to my Lib version, I hope you'll take note of it. Thanks for providing a multimodal graph benchmark!

**Comment by CharliedoD** [comment]
Another small problem, the lp-edge-split in the dataset Sports doesn't specify what type of edge split it is, 'hard' or others?

**Comment by CharliedoD** [comment]
I would also like to know, what is the form of the features in the dataset? Is the first half along the feature dimension text, and the second half vision?

**Comment by jwzhi** [comment]
The 2D stuff might be an version difference. I didn't do that on my side. 
Sorry for the naming ambiguity. For Amazon-Sports and Amazon-cloth, we provide hard negatives, so in the code it is named as '-hard'. I just corrected that. Thanks for bringing this up.
